; Supervisor configuration 
; Reference: http://supervisord.org/configuration.html

; Define supervisor process
[supervisord]
nodaemon = true
user = root
loglevel = warn
strip_ansi = true

; Enable RPC
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

; Shell
[supervisorctl]
serverurl = unix:///dev/shm/supervisor.sock
username = supervisor
password = supervisor_password

; Configure the server and socket
; Note: password is required to silence a warning
[unix_http_server]
file = /dev/shm/supervisor.sock
chmod = 0700
username = supervisor
password = supervisor_password

; Services defined separately
[include]
files = /etc/supervisor/conf.d/*.conf
