# Send messages to stdout/stderr by priority
# https://wiki.archlinux.org/title/rsyslog#Severity_levels

# stdout: debug, info, notice, warning
*.debug;*.!err -/dev/stdout

# stderr: err, crit, alert, emerg
*.err -/dev/stderr
